version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date` 
      - mvn -version
      - mvn -verify
      - mvn install
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -package
      - mvn -package
artifacts:
  files:
    - target/awsproject3-0.0.1-SNAPSHOT.war
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - scripts/stop_server
  discard-paths: yes
